module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    height: {
      '0': 0,
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': ' 2.5rem',
      '12': ' 3rem',
      '16': ' 4rem',
      '20': ' 5rem',
      '24': ' 6rem',
      '32': ' 8rem',
      '40': ' 10rem',
      '48': ' 12rem',
      '56': ' 14rem',
      '64': ' 16rem',
      'auto': 'auto',
      'px': ' 1px',
      'full': '100%',
      'screen': '100vh',
      '1/2': '50%',
      '1/4': '25%',
      '2/3': '66.66666%',
    },
    padding: {
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '28': '7rem',
      '30': '7.5rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem'
    },
    screens: {
      'xs': '512px',
      // => @media (min-width: 512px) { ... }

      'sm': '640px',
      // => @media (min-width: 640px) { ... }

      'md': '768px',
      // => @media (min-width: 768px) { ... }

      'lg': '1024px',
      // => @media (min-width: 1024px) { ... }

      'xl': '1280px',
      // => @media (min-width: 1280px) { ... }
    },
    maxWidth: {
      'none': ' none',
      'xxs': ' 16rem',
      'xs': ' 20rem',
      'sm': ' 24rem',
      'md': ' 28rem',
      'lg': ' 32rem',
      'xl': ' 36rem',
      '2xl': ' 42rem',
      '3xl': ' 48rem',
      '4xl': ' 56rem',
      '5xl': ' 64rem',
      '6xl': ' 72rem',
      'full': ' 100%',
      'screen-sm': ' 640px',
      'screen-md': ' 768px',
      'screen-lg': ' 1024px',
      'screen-xl': ' 1280px',
    },
    width: {
      '0': ' 0',
      '1': ' 0.25rem',
      '2': ' 0.5rem',
      '3': ' 0.75rem',
      '4': ' 1rem',
      '5': ' 1.25rem',
      '6': ' 1.5rem',
      '8': ' 2rem',
      '10': ' 2.5rem',
      '12': ' 3rem',
      '16': ' 4rem',
      '20': ' 5rem',
      '24': ' 6rem',
      '32': ' 8rem',
      '40': ' 10rem',
      '48': ' 12rem',
      '56': ' 14rem',
      '64': ' 16rem',
      '72': ' 18rem',
      '80': ' 20rem',
      'auto': ' auto',
      'px': ' 1px',
      '1/2': ' 50%',
      '1/3': ' 33.333333%',
      '2/3': ' 66.666667%',
      '1/4': ' 25%',
      '2/4': ' 50%',
      '3/4': ' 75%',
      '1/5': ' 20%',
      '2/5': ' 40%',
      '3/5': ' 60%',
      '4/5': ' 80%',
      '1/6': ' 16.666667%',
      '2/6': ' 33.333333%',
      '3/6': ' 50%',
      '4/6': ' 66.666667%',
      '5/6': ' 83.333333%',
      '1/12': ' 8.333333%',
      '2/12': ' 16.666667%',
      '3/12': ' 25%',
      '4/12': ' 33.333333%',
      '5/12': ' 41.666667%',
      '6/12': ' 50%',
      '7/12': ' 58.333333%',
      '8/12': ' 66.666667%',
      '9/12': ' 75%',
      '10/12': ' 83.333333%',
      '11/12': ' 91.666667%',
      'full': ' 100%',
      'screen': ' 100vw',
    },
    fontFamily: {
      'sans': ['-apple-system', 'BlinkMacSystemFont'],
      'serif': ['Georgia', 'Cambria'],
      'mono': ['SFMono-Regular', 'Menlo'],
      'cookie': ['Cookie', 'cursive']
    }
  },
  variants: {
    variants: {
      accessibility: ['responsive', 'focus'],
      alignContent: ['responsive'],
      alignItems: ['responsive'],
      alignSelf: ['responsive'],
      appearance: ['responsive'],
      backgroundAttachment: ['responsive'],
      backgroundClip: ['responsive'],
      backgroundColor: ['responsive', 'hover', 'focus'],
      backgroundImage: ['responsive'],
      gradientColorStops: ['responsive', 'hover', 'focus'],
      backgroundOpacity: ['responsive', 'hover', 'focus'],
      backgroundPosition: ['responsive'],
      backgroundRepeat: ['responsive'],
      backgroundSize: ['responsive'],
      borderCollapse: ['responsive'],
      borderColor: ['responsive', 'hover', 'focus'],
      borderOpacity: ['responsive', 'hover', 'focus'],
      borderRadius: ['responsive'],
      borderStyle: ['responsive'],
      borderWidth: ['responsive'],
      boxShadow: ['responsive', 'hover', 'focus'],
      boxSizing: ['responsive'],
      container: ['responsive'],
      cursor: ['responsive'],
      display: ['responsive'],
      divideColor: ['responsive'],
      divideOpacity: ['responsive'],
      divideStyle: ['responsive'],
      divideWidth: ['responsive'],
      fill: ['responsive'],
      flex: ['responsive'],
      flexDirection: ['responsive'],
      flexGrow: ['responsive'],
      flexShrink: ['responsive'],
      flexWrap: ['responsive'],
      float: ['responsive'],
      clear: ['responsive'],
      fontFamily: ['responsive'],
      fontSize: ['responsive'],
      fontSmoothing: ['responsive'],
      fontVariantNumeric: ['responsive'],
      fontStyle: ['responsive'],
      fontWeight: ['responsive', 'hover', 'focus'],
      height: ['responsive'],
      inset: ['responsive'],
      justifyContent: ['responsive'],
      justifyItems: ['responsive'],
      justifySelf: ['responsive'],
      letterSpacing: ['responsive'],
      lineHeight: ['responsive'],
      listStylePosition: ['responsive'],
      listStyleType: ['responsive'],
      margin: ['responsive'],
      maxHeight: ['responsive'],
      maxWidth: ['responsive'],
      minHeight: ['responsive'],
      minWidth: ['responsive'],
      objectFit: ['responsive'],
      objectPosition: ['responsive'],
      opacity: ['responsive', 'hover', 'focus'],
      order: ['responsive'],
      outline: ['responsive', 'focus'],
      overflow: ['responsive'],
      overscrollBehavior: ['responsive'],
      padding: ['responsive'],
      placeContent: ['responsive'],
      placeItems: ['responsive'],
      placeSelf: ['responsive'],
      placeholderColor: ['responsive', 'focus'],
      placeholderOpacity: ['responsive', 'focus'],
      pointerEvents: ['responsive'],
      position: ['responsive'],
      resize: ['responsive'],
      space: ['responsive'],
      stroke: ['responsive'],
      strokeWidth: ['responsive'],
      tableLayout: ['responsive'],
      textAlign: ['responsive'],
      textColor: ['responsive', 'hover', 'focus'],
      textOpacity: ['responsive', 'hover', 'focus'],
      textDecoration: ['responsive', 'hover', 'focus'],
      textTransform: ['responsive'],
      userSelect: ['responsive'],
      verticalAlign: ['responsive'],
      visibility: ['responsive'],
      whitespace: ['responsive'],
      width: ['responsive'],
      wordBreak: ['responsive'],
      zIndex: ['responsive'],
      gap: ['responsive'],
      gridAutoFlow: ['responsive'],
      gridTemplateColumns: ['responsive'],
      gridColumn: ['responsive'],
      gridColumnStart: ['responsive'],
      gridColumnEnd: ['responsive'],
      gridTemplateRows: ['responsive'],
      gridRow: ['responsive'],
      gridRowStart: ['responsive'],
      gridRowEnd: ['responsive'],
      transform: ['responsive'],
      transformOrigin: ['responsive'],
      scale: ['responsive', 'hover', 'focus'],
      rotate: ['responsive', 'hover', 'focus'],
      translate: ['responsive', 'hover', 'focus'],
      skew: ['responsive', 'hover', 'focus'],
      transitionProperty: ['responsive'],
      transitionTimingFunction: ['responsive'],
      transitionDuration: ['responsive'],
      transitionDelay: ['responsive'],
      animation: ['responsive', 'hover']
    }
  },
  plugins: [],
}
